---
- name: Create a ansible user
  hosts: web
  vars_files: vars/secret.yml
  tasks:
    - name: Create user from secret.yml
      user:
        name: "{{ username }}"
        password: "{{ pwhash }}" 
